GET http://localhost:8080/products

###
GET http://localhost:8080/customers

###
POST http://localhost:8080/customer
Content-Type: application/json

{
    "name": "Ilia Kuchmin",
    "email": "kuchmin@haulmont.com"
}

### 
POST http://localhost:8080/inventory/supply
Content-Type: application/json

{
    "productId": 1,
    "cityId": 1,
    "amount": 1
}"

