services:
    orders:
        image: cr.yandex/crpbk8g4u7lsdfqsm38s/orders:${orders_version}
        restart: "no"
        ports:
            - "8080:8080"
        environment:
            SPRING_DATASOURCE_URL: ${datasource_url}
            SPRING_DATASOURCE_USERNAME: ${datasource_username}
            SPRING_DATASOURCE_PASSWORD: ${datasource_password}
            SPRING_PROFILES_ACTIVE: yc
            STORAGE_URL: https://storage.yandexcloud.net
            STORAGE_BUCKET: ${storage_bucket}
            STORAGE_ACCESSKEY: ${storage_access_key}
            STORAGE_SECRETKEY: ${storage_secret_key}
            SPRING_KAFKA_BOOTSTRAPSERVERS: ${kafka_url}
            KAFKA_USER: ${kafka_user}
            KAFKA_PASSWORD: ${kafka_password}

networks:
    main:
